apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: api
          image: debian:bullseye-slim
          command:
            - "/script/run.sh"
          envFrom:
            - configMapRef:
                name: app1-configmap
          volumeMounts:
            - name: script
              mountPath: /script
      volumes:
        - name: script
          configMap:
            name: script-configmap
            defaultMode: 0755 # Add exec permissions
